data_root: '/home/cbtil/ST_proj/data/Breast_cancer/'
SR_times: 10
gene_num: 50

############ train
resume_path: './models/toy-t2i-noimg.ckpt'
dataset_choose: 'Xenium' ## Xenium Visium NBME Melanoma
batch_size: 4
logger_freq: 300
_every_n_train_steps: 20000
learning_rate: 1e-5
modelname: 'cldm_t2i-imgtxt'
seed: 512
sd_locked: False
only_mid_control: False

############ test
resume_path_test: './logs/2024-05-14T20-18-24_cldm_t2i-onlytxt_Xenium/checkpoints/epoch=5-step=11099.ckpt'
guess_mode: False



model:
  target: cldm.cldm_t2i.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "HRST"
    control_LRST: "LRST"
    control_WSI: "WSI"
    gene_caption: "gene_caption"
#    gene_class: "gene_class"
    control_Gene_index_map: "Gene_index_map"

    image_size: 64 # unused
    channels: 4 # original 4
    cond_stage_trainable: False # ####################################################
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False

    force_null_conditioning: False # ####################################################

    control_stage_config:
      target: cldm.cldm_t2i.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4  ]
        num_heads: 8
        use_spatial_transformer: True # ####################################################
        transformer_depth: 1
        context_dim: 768 # ####################################################
        use_checkpoint: True
        legacy: False

    unet_config:
      target: cldm.cldm_uncon.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True # ####################################################
        transformer_depth: 1
        context_dim: 768 # ####################################################
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4 #noused
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256 #noused
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: #'__is_unconditional__'
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder