data_root: 'your data dir/Xenium/'
SR_times: 10
gene_num: 200

############ test
resume_path_test: ''
guess_mode: False

############ train
resume_path: 'toy-uncon.ckpt'
dataset_choose: 'Xenium' ## Xenium Visium NBME Melanoma
batch_size: 4
logger_freq: 500
_every_n_train_steps: 2000
learning_rate: 1e-5
modelname: 'cldm_ours'
seed: 512
sd_locked: False
only_mid_control: False




model:
  target: cldm.cldm_uncon.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "HRST"
    control_LRST: "LRST"
    control_WSI: "WSI"
#    gene_caption: "gene_caption"
#    gene_class: "gene_class"
    control_Gene_index_map: "Gene_index_map"


    image_size: 64 # unused
    channels: 3 # original 4
#    cond_stage_trainable: false
#    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False

    force_null_conditioning: True # ####################################################

    control_stage_config:
      target: cldm.cldm_uncon.ControlNet
      params:
        image_size: 64 # unused
        in_channels: 3
        hint_channels: 3
        model_channels: 224
        attention_resolutions: [ 8, 4, 2 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3, 4 ]
        num_heads: 32
#        use_spatial_transformer: False # ####################################################
#        transformer_depth: 1
#        context_dim: 768 # ####################################################
        use_checkpoint: True
#        legacy: False

    unet_config:
      target: cldm.cldm_uncon.ControlledUnetModel
      params:
        image_size: 64 # unused
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions: [ 8, 4, 2 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 3, 4 ]
        num_heads: 32
#        use_spatial_transformer: False # ####################################################
#        transformer_depth: 1
#        context_dim: 768 # ####################################################
        use_checkpoint: True
#        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3 #noused
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256 #noused
          in_channels: 3
          out_ch: 200
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: '__is_unconditional__'